// Supplier metadata is deliberately separate from the estimator price book.
// Cost/sell values still come from the original Excel catalogue until the pricing pass.
// Add verified product links here as materials are matched to current supplier products.
window.GF_SUPPLIER_DATA={
"mat-038":{supplier:"IBT Merchants",supplierSku:"FENCE022100CPP42",supplierTitle:"Redwood Capping Rail Treated 25MM x 95MM x 4.2 METRE 70% PEFC Certified",supplierUrl:"https://www.ibtmerchants.co.uk/product/1463/fencing-accessories/6649/redwood-capping-rail-treated-25mm-x-95mm-x-4-2-metre-70-pefc-certified",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/IMG_2814_opt.jpg",supplierVerified:true},
"mat-040":{supplier:"IBT Merchants",supplierSku:"AGGREGATES0230",supplierTitle:"Harvest Gold Solent Decorative Chips IBT Bulk Bag",supplierUrl:"https://www.ibtmerchants.co.uk/product/1247/decorative-chips/5093/harvest-gold-solent-decorative-chips-ibt-bulk-bag",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/Harvest-gold-wet.jpg",supplierVerified:true},
"mat-044":{supplier:"IBT Merchants",supplierSku:"DECK090090NP1250",supplierTitle:"Decking Newel Post Colonial 82mm x 82mm x 1250mm DEP12CAP",supplierUrl:"https://ibtmerchants.co.uk/product/1459/timber-decking-accessories/5357/decking-newel-post-colonial-82mm-x-82mm-x-1250mm-dep12cap",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/colonial-newel-post-detail_1024x1024_a0919a34-a653-4ee6-94ef-d716d9861821_1024x1024.jpg",supplierVerified:true},
"mat-045":{supplier:"IBT Merchants",supplierSku:"DECK041041SPC0L",supplierTitle:"Decking Spindle Colonial 41mm x 41mm x 895mm DED90",supplierUrl:"https://ibtmerchants.co.uk/product/1459/timber-decking-accessories/5355/decking-spindle-colonial-41mm-x-41mm-x-895mm-ded90",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/spindle-colonial-31pKCi4J-GL._SY355_.jpg",supplierVerified:true},
"mat-057":{supplier:"IBT Merchants",supplierSku:"DECKSTAIR3",supplierTitle:"3 Step Stringer 868mm x 245mm DS3",supplierUrl:"https://ibtmerchants.co.uk/product/1459/timber-decking-accessories/5353/3-step-stringer-868mm-x-245mm-ds3",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/DECKSTAIR3.jpg",supplierVerified:true},
"mat-058":{supplier:"IBT Merchants",supplierSku:"DECKSTAIR5",supplierTitle:"5 Step Stringer 1447mm x 48mm x 245mm DS5",supplierUrl:"https://ibtmerchants.co.uk/product/1459/timber-decking-accessories/5354/5-step-stringer-1447mm-x-48mm-x-245mm-ds5",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/DECKSTAIR5.jpg",supplierVerified:true},
"mat-059":{supplier:"IBT Merchants",supplierSku:"DECKPANELC",supplierTitle:"Crosshatch Decking Panel 1135mm x 760mm x 32mm",supplierUrl:"https://ibtmerchants.co.uk/product/1459/timber-decking-accessories/5350/crosshatch-decking-panel-1135mm-x-760mm-x-32mm-dehat",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/DECKPANELC.jpg",supplierVerified:true},
"mat-062":{supplier:"IBT Merchants",supplierSku:"DECKPANELS",supplierTitle:"Sunburst Decking Panel 1135mm x 760mm x 32mm",supplierUrl:"https://ibtmerchants.co.uk/product/1459/timber-decking-accessories/5351/sunburst-decking-panel-1135mm-x-760mm-x-32mm-desun",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/DECKPANELS.jpg",supplierVerified:true},
"mat-069":{supplier:"IBT Merchants",supplierSku:"DECK02814542PNP",supplierTitle:"Redwood Treated Decking 28mm x 145mm x 4.2 Metre Profile A73",supplierUrl:"https://www.ibtmerchants.co.uk/product/1460/timber-decking-board/5010/redwood-treated-decking-28mm-x-145mm-x-4-2-metre-profile-a73",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/DECKING-APR19.png",supplierVerified:true},
"mat-073":{supplier:"IBT Merchants",supplierSku:"DECK090090NP1250",supplierTitle:"Decking Newel Post Colonial 82mm x 82mm x 1250mm DEP12CAP",supplierUrl:"https://ibtmerchants.co.uk/product/1459/timber-decking-accessories/5357/decking-newel-post-colonial-82mm-x-82mm-x-1250mm-dep12cap",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/colonial-newel-post-detail_1024x1024_a0919a34-a653-4ee6-94ef-d716d9861821_1024x1024.jpg",supplierVerified:true},
"mat-074":{supplier:"IBT Merchants",supplierSku:"DECKPATR1250",supplierTitle:"Decking Post Patrice Newel 82mm x 82mm x 1250mm DEP12CB",supplierUrl:"https://ibtmerchants.co.uk/product/1459/timber-decking-accessories/5352/decking-post-patrice-newel-82mm-x-82mm-x-1250mm-dep12cb",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/patrice-img-2140-900x590.jpg",supplierVerified:true},
"mat-075":{supplier:"IBT Merchants",supplierSku:"DECK041041SPP",supplierTitle:"Decking Spindle R4A 41mm x 41mm x 895mm 41PBTR",supplierUrl:"https://ibtmerchants.co.uk/product/1459/timber-decking-accessories/5356/decking-spindle-r4a-41mm-x-41mm-x-895mm-41pbtr",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/Square-Spindle.jpg",supplierVerified:true},
"mat-076":{supplier:"IBT Merchants",supplierSku:"DECK041041SPC0L",supplierTitle:"Decking Spindle Colonial 41mm x 41mm x 895mm DED90",supplierUrl:"https://ibtmerchants.co.uk/product/1459/timber-decking-accessories/5355/decking-spindle-colonial-41mm-x-41mm-x-895mm-ded90",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/spindle-colonial-31pKCi4J-GL._SY355_.jpg",supplierVerified:true},
"mat-077":{supplier:"IBT Merchants",supplierSku:"DECK041041SPP",supplierTitle:"Decking Spindle R4A 41mm x 41mm x 895mm 41PBTR",supplierUrl:"https://ibtmerchants.co.uk/product/1459/timber-decking-accessories/5356/decking-spindle-r4a-41mm-x-41mm-x-895mm-41pbtr",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/Square-Spindle.jpg",supplierVerified:true},
"mat-079":{supplier:"IBT Merchants",supplierSku:"DECK02814542PNP",supplierTitle:"Redwood Treated Decking 28mm x 145mm x 4.2 Metre Profile A73",supplierUrl:"https://www.ibtmerchants.co.uk/product/1460/timber-decking-board/5010/redwood-treated-decking-28mm-x-145mm-x-4-2-metre-profile-a73",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/DECKING-APR19.png",supplierVerified:true},
"mat-091":{supplier:"IBT Merchants",supplierSku:"AGGREGATES0220",supplierTitle:"Ledmore Marble 20mm IBT Bulk Bag (Skye Marble)",supplierUrl:"https://www.ibtmerchants.co.uk/product/1247/decorative-chips/5092/ledmore-marble-20mm-ibt-bulk-bag-skye-marble",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/IMG_2219.jpg",supplierVerified:true},
"mat-092":{supplier:"IBT Merchants",supplierSku:"AGGREGATES0500",supplierTitle:"Ledmore Marble 20MM 25KG IBT Bag (Skye Marble)",supplierUrl:"https://www.ibtmerchants.co.uk/product/5130/ledmore-marble-20mm-25kg-ibt-bag-skye-marble",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/IMG_2219.jpg",supplierVerified:true},
"mat-099":{supplier:"IBT Merchants",supplierSku:"AGGREGATES0230",supplierTitle:"Harvest Gold Solent Decorative Chips IBT Bulk Bag",supplierUrl:"https://www.ibtmerchants.co.uk/product/1247/decorative-chips/5093/harvest-gold-solent-decorative-chips-ibt-bulk-bag",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/Harvest-gold-wet.jpg",supplierVerified:true},
"mat-100":{supplier:"IBT Merchants",supplierSku:"VARIES BY SIZE",supplierTitle:"20mm Harvest Gold (Solent)",supplierUrl:"https://www.ibtmerchants.co.uk/product/51/decorative-aggregates/263/20mm-harvest-gold-solent",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/Harvest-gold-wet.jpg",supplierVerified:true},
"mat-101":{supplier:"IBT Merchants",supplierSku:"AGGREGATES0260",supplierTitle:"Spey Decorative Chips 20mm IBT Bulk Bag",supplierUrl:"https://www.ibtmerchants.co.uk/product/1247/decorative-chips/5098/spey-decorative-chips-20mm-ibt-bulk-bag",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/20mm--speystones--wet.jpg",supplierVerified:true},
"mat-102":{supplier:"IBT Merchants",supplierSku:"VARIES BY SIZE",supplierTitle:"20mm Spey",supplierUrl:"https://www.ibtmerchants.co.uk/product/51/decorative-aggregates/266/20mm-spey",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/20mm--speystones--wet.jpg",supplierVerified:true},
"mat-103":{supplier:"IBT Merchants",supplierSku:"AGGREGATES0312",supplierTitle:"White Marble Chip 20mm IBT Bulk Bag",supplierUrl:"https://www.ibtmerchants.co.uk/product/1247/decorative-chips/5103/white-marble-chip-20mm-ibt-bulk-bag",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/white--marble--20mm-wet.jpg",supplierVerified:true},
"mat-104":{supplier:"IBT Merchants",supplierSku:"AGGREGATES0405",supplierTitle:"White Marble Chip Chips 20MM 25KG IBT Bag",supplierUrl:"https://ibtmerchants.co.uk/product/1247/decorative-chips/5118/white-marble-chip-chips-20mm-25kg-ibt-bag",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/white--marble--20mm-wet.jpg",supplierVerified:true},
"mat-107":{supplier:"IBT Merchants",supplierSku:"AGGREGATES0230",supplierTitle:"Harvest Gold Solent Decorative Chips IBT Bulk Bag",supplierUrl:"https://www.ibtmerchants.co.uk/product/1247/decorative-chips/5093/harvest-gold-solent-decorative-chips-ibt-bulk-bag",supplierImage:"https://www.ibtmerchants.co.uk/images/mediumimages/products/Harvest-gold-wet.jpg",supplierVerified:true}
};
